# Generated by Django 3.2.7 on 2021-09-11 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.account'),
        ),
    ]
