# Generated by Django 3.2.7 on 2021-09-11 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_image_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='size_for_premium_account',
            new_name='size_large',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='size_for_basic_account',
            new_name='size_small',
        ),
    ]
